### ISSUE TITLE
Games dispeared after adding a tag to 1.

### ISSUE THREAD

**Issue by markmorris** [tkashkin/GameHub#99]
After adding a tag to a game (Outlast) all games disappeared, nothing i can do to change it, i toggle all settings including merge games, still blank.

No matter what its blank, this is 10 mins after app is loaded to test if it was slow loading times.
![screenshot from 2018-10-10 10-31-58](https://user-images.githubusercontent.com/7857906/46727728-129a2080-cc79-11e8-9a40-5d044c0ec01d.png)

Loving the app, lets get it fixed up!

**Comment by tkashkin** [comment]
Try to switch some tags in filters popover (tag icon on headerbar).

It should display all games without any filtering if all or no tags are selected.

It should display games that have at least one of selected tags otherwise.

You may have encountered [this bug](https://github.com/tkashkin/GameHub/issues/47#issuecomment-423770746). It is already fixed in `dev` branch.

**Comment by markmorris** [comment]
Tried everything. Switching back between views, games etc etc does nothing.

Thank you for your fast replies.

![screenshot from 2018-10-10 11-00-05](https://user-images.githubusercontent.com/7857906/46728879-c00e3380-cc7b-11e8-937f-7470f30f6002.png)

**Comment by tkashkin** [comment]
Ok, then it should be something new. I'll take a look later today (or in a few days depending on free time).

Distro, app version, reproduce steps and logs will be helpful.

**Comment by markmorris** [comment]
Currently using ElementaryOS, cant find app version anywhere but i only installed today, so assuming its the latest.

All i did was add Outlast to favourites, that broke everything. Even removing from favourites did not fix.

**Comment by markmorris** [comment]
Example of **Show non-native games** bug.

![screenshot from 2018-10-10 12-10-02](https://user-images.githubusercontent.com/7857906/46732470-7b879580-cc85-11e8-89c5-13a75a57f6cb.png)

![screenshot from 2018-10-10 12-10-13](https://user-images.githubusercontent.com/7857906/46732484-82aea380-cc85-11e8-86c4-66d959d94234.png)

**Comment by tkashkin** [comment]
It's a weird issue, I'm not sure yet why that happens.

I don't get it with my locally built, not installed version, but I do get it with a packages and AppImages built on AppVeyor or launchpad (btw PPA for Ubuntu-based distros is now available).
More weird is that I get it even with a deb package built on my system.

Bug should be somewhere in native/non-native games detection.
If you enable "Use compat layers" option, it should be mostly ok, except all games being "non-native".

---

Try to build it on your system and see if you'll have the same result as me.
Here are exact commands I test with:
```bash
meson build --prefix=/usr -Ddistro=debian --buildtype=debug
cd build
ninja && src/com.github.tkashkin.gamehub --debug
```

---

> Could this error have anything to do with me having 280+ games?

Good assumption, but no, it's definitely not a problem. :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/2003017/46756669-aba85600-ccd0-11e8-9429-8801a15ac7e7.png)

**Comment by tkashkin** [comment]
I have found a reason for this weird behavior. It was due to compiler optimizations.
There was a discussion of this issue in #103.

Packages built on AppVeyor should work properly. I'm still trying to pass required options to launchpad to disable optimizations for PPA builds.

**Comment by tkashkin** [comment]
@markmorris, @Hedronmx launchpad builds are now built without optimizations.

**Comment by Hedronmx** [comment]
Sweet, anyway to check changelogs?

**Comment by tkashkin** [comment]
> Sweet, anyway to check changelogs?

I'm too lazy to document all changes, so best thing you can do is to check [commits list](https://github.com/tkashkin/GameHub/commits/dev).

**Comment by Hedronmx** [comment]
I see, thank you! Please let me know when I can donate.
